version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: beabadoobee
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  insta-alerts:
    build: insta-notifications/.
    environment:
      USERNAME: user
      PASSWORD: pass
      CHANNEL_ID: id
      TOKEN: token
      BEACORD: id

volumes:
  db-data: {}