version: "3.9"
services:
  bot:
    build: .
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beabadoobee
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}